### ISSUE TITLE
Option to export to STL or to a normal freecad objetct

### ISSUE THREAD

**Issue by Obijuan** [JMG1/VoxelWorkbench#1]
Hi Javi!

I really really really like your Pluging!!!! It is amazing!!!!!!!  Thanks a lot for sharing!!

It has a great potential for attracking kids to the FreeCAD world. It is like playing minecraft!!

It would be great if this workbench had the option to export the generated figure to a standard Freecad figure, so that it can be exported to STL or reused with other parts.  I am thinking about  the kids designing their parts and then printing them... so easily...

Thanks again! Great work!!! :-)

**Comment by JMG1** [comment]
Thanks for your feedback!! :D

I added this issue to the TODO list.
